### ISSUE TITLE
`twbs-font-path` shows up in compiled css file

### ISSUE THREAD

**Issue by kapooostin** [roots/roots-sass#3]
Sass compiles without errors but minified file contains this:

``` css
@font-face {
font-family:'Glyphicons Halflings';src:url(twbs-font-path("bootstrap/glyphicons-halflings-regular.eot"));src:url(twbs-font-path("bootstrap/glyphicons-halflings-regular.eot?#iefix")) format("embedded-opentype"),url(twbs-font-path("bootstrap/glyphicons-halflings-regular.woff")) format("woff"),url(twbs-font-path("bootstrap/glyphicons-halflings-regular.ttf")) format("truetype"),url(twbs-font-path("bootstrap/glyphicons-halflings-regular.svg#glyphicons-halflingsregular")) format("svg")
}
```
